version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=production
    restart: always
    volumes:
      - api_data:/app/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
    restart: always
    volumes:
      - web_data:/app/data

volumes:
  api_data:
  web_data:
